# -*- coding: utf-8 -*-
"""modified_transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qim5dQpdN8gjqWvFTsd3wbCw6uPHvJb3
"""

!pip install transformers datasets accelerate peft torch trl

#Loader
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments
from trl import SFTTrainer
from peft import LoraConfig

#Loading small pre-trained model
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

#Loading dataset
import json

# Example data for data.jsonl, ensuring it's valid JSON Lines format
example_data = [
    {"messages": [{"role": "user", "content": "Hello!"}, {"role": "assistant", "content": "Hi there!"}]},
    {"messages": [{"role": "user", "content": "How are you?"}, {"role": "assistant", "content": "I'm doing great, thank you!"}]},
    {"messages": [{"role": "user", "content": "What is your purpose?"}, {"role": "assistant", "content": "I am a large language model, trained by Google."}]}
]

# Write the example data to data.jsonl
with open("data.jsonl", "w") as f:
    for entry in example_data:
        f.write(json.dumps(entry) + "\n")

dataset = load_dataset("json", data_files="data.jsonl", split="train")

#Configuation of LoRA
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"], #Layers to modify
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"

)

#Training arguments
training_args = TrainingArguments(
    output_dir="./chat-model",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    num_train_epochs=3,
    fp16 = True,
    logging_steps=10,

)

#Initialize the trainer
def formatting_prompts_func(examples):
  texts = []
  for messages in examples["messages"]:
    text = tokenizer.apply_chat_template(messages, tokenize=False)
    texts.append(text)
  return {"texts": texts}

dataset = dataset.map(formatting_prompts_func, batched=True)

trained = SFTTrainer(
    model=model,
    train_dataset = dataset,
    args=training_args,
    peft_config=peft_config
)

trained.train()

trained.save_model('./my-chat-model')

#Inference time
import torch

model_path = "./my-chat-model"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path)

conversation = []

while True:
  user_input = input("You: " )
  if user_input.lower() == "quit":
    break

  #Adding user message to history
  conversation.append({"role": "user", "content": user_input})

  #Apply the chat template to the history
  model_input = tokenizer.apply_chat_template(conversation, tokenize=False, add_generation_prompt=True)
  inputs = tokenizer.encode(model_input, return_tensors="pt")

  #Generate response
  outputs = model.generate(inputs, max_new_tokens=256)
  response = tokenizer.decode(outputs[0], skip_special_tokens=True)

  #Extract only new assistant text
  assistant_message = response.split("Assistant:")[-1].strip()

  print(f"Bot:{assistant_message}")

  conversation.append({"role": "assistant", "content": assistant_message})